name: Compile Sketches

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  compile-sketches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # See: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketches
        uses: arduino/compile-sketches@v1
        with:
          fqbn: arduino:avr:uno
          sketch-paths: |
            - tests/Test
            - tests/Test2
            - examples/ServoLib_Demo
            - examples/ServoLib_LnRActuator_Demo
            - examples/ServoLib_PolynomialFit_Demo
            - examples/ServoShield_Demo
            - examples/ServoShield_LnRActuator_Demo
            - examples/ServoShield_PencilLeadDrive
          libraries: |
            - source-url: https://github.com/mmurdoch/arduinounit.git
            - source-url: https://github.com/arduino-libraries/Servo.git
            - source-path: .
